repos:
  - repo: local
    hooks:
      - id: qr-code-generator
        name: Run QR Code Generator
        entry: python qr_code_generator.py
        language: system
        types: [python]
        always_run: true
      - id: pytest
        name: Run pytest
        entry: pytest
        language: system
        types: [python]
        always_run: true
